AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  authentication-lambda

  Sample SAM Template for authentication-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: AuthenticationFunction
      Handler: authentication.App::handleRequest
      Runtime: java17
      VpcConfig:
        SecurityGroupIds:
          - sg-0ac86d0cb94204aaa
        SubnetIds:
          - subnet-6a38f00c
          - subnet-1bdec125
          - subnet-6099022d
          - subnet-97fc2ab6
          - subnet-90b064cf
          - subnet-c4c64bca
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Authentication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AuthenticationApi:
    Description: "API Gateway endpoint URL for Prod stage for Authentication function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  AuthenticationFunction:
    Description: "Authentication Lambda Function ARN"
    Value: !GetAtt AuthenticationFunction.Arn
  AuthenticationFunctionIamRole:
    Description: "Implicit IAM Role created for Authentication function"
    Value: !GetAtt AuthenticationFunctionRole.Arn
